### ISSUE TITLE
runtests.jl: Unsupported backend gadfly 

### ISSUE THREAD

**Issue by tomerarnon** [zsunberg/LightDarkPOMDPs.jl#1]
Hello,
I recently came across this code, and am trying to run it as an introduction to the LightDark pomdp in Julia. For context, my goal is ultimately to compare the performance of several pomdp solvers using the LightDark pomdp as a kind of "benchmark".
When running `runtests.jl`, including any of the `plot` functions at the end, I get the following error message:

> WARNING: Backend gadfly has been deprecated.  It may not work as originally intended.
> ERROR: Unsupported backend gadfly
>  in _backend_instance(::Symbol) at /Users/tomer/.julia/v0.5/Plots/src/backends.jl:11
>  in backend at /Users/tomer/.julia/v0.5/Plots/src/backends.jl:208 [inlined]
>  in pickDefaultBackend() at /Users/tomer/.julia/v0.5/Plots/src/backends.jl:153
>  in backend() at /Users/tomer/.julia/v0.5/Plots/src/backends.jl:171
>  in Plots.Plot{T<:Plots.AbstractBackend}() at /Users/tomer/.julia/v0.5/Plots/src/types.jl:85
>  in #plot#263(::Array{Any,1}, ::Function, ::LightDarkPOMDPs.LightDark2D, ::Vararg{Any,N}) at /Users/tomer/.julia/v0.5/Plots/src/plot.jl:50
>  in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::LightDarkPOMDPs.LightDark2D, ::POMDPToolbox.POMDPHistory{StaticArrays.SVector{2,Float64},StaticArrays.SVector{2,Float64},StaticArrays.SVector{2,Float64},LightDarkPOMDPs.SymmetricNormal2}, ::Vararg{POMDPToolbox.POMDPHistory{StaticArrays.SVector{2,Float64},StaticArrays.SVector{2,Float64},StaticArrays.SVector{2,Float64},LightDarkPOMDPs.SymmetricNormal2},N}) at ./<missing>:0

Are you aware of this issue and of something that can fix it?
I'm not sure what to expect from this code, and plotting the result as intended would be very helpful.

Thanks in advance.

**Comment by zsunberg** [comment]
Hi @tomerarnon ,

Sorry for the delayed response - I am out of the country with limited time to work. Thanks for pointing this out! I have tried to add plotting to the stuff that is tested, and set the default Plots.jl backend to Plotly (using `plotly()`) so that things are more consistent.

I am not sure why your system was trying to use gadfly - perhaps that is the only Plots.jl backend you have installed? You will probably get the best results with PyPlot.

Let me know if you have any more questions - this package unfortunately isn't well-documented.
